version: '3'
services:
  web:
    build: .
    command: sh -c " python manage.py migrate &&python insert_data_to_db.py && python manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
      DB_NAME: 'db'
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: investment
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 80:80
    depends_on:
      - db

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    depends_on:
      - db

  celery-worker:
    build: .
    environment:
      CELERY_URL: 'redis'
      DB_NAME: 'db'
    restart: always
    command: celery -A celery_worker.celery_app worker --loglevel=info -P solo
    depends_on:
      - redis

  celery-beat:
    build: .
    restart: always
    environment:
      CELERY_URL: 'redis'
      DB_NAME: 'db'
    command: celery -A celery_worker.celery_app beat --loglevel=info
    depends_on:
      - redis