# Generated by Django 4.2 on 2023-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='show_to_all',
            field=models.BooleanField(default=True),
        ),
    ]
