# Generated by Django 4.2 on 2023-05-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contracts_show_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='en_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
